# Generated by Django 3.1.1 on 2020-09-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200915_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='foto_portada',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='foto_restaurante',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='media/'),
        ),
    ]
