# Generated by Django 3.1.1 on 2020-09-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20200916_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='foto_qr',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='media/'),
        ),
    ]
