# Generated by Django 3.1.1 on 2020-09-17 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.plan', verbose_name='Plan')),
            ],
        ),
    ]
