# Generated by Django 3.1.1 on 2020-09-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_plandetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='plandetail',
            options={'verbose_name': 'Plan Detalle', 'verbose_name_plural': 'Plan Detalles'},
        ),
    ]
