# Generated by Django 3.1.1 on 2020-09-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20200917_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='link',
            field=models.TextField(default='#', verbose_name='link'),
        ),
    ]
