# Generated by Django 3.1.1 on 2020-09-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='foto_portada_secundaria',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='media/'),
        ),
    ]
