# Generated by Django 3.1.1 on 2020-09-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurant_foto_portada_secundaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('cordobas', 'C$'), ('dolares', '$')], default='C$', max_length=50, verbose_name='Moneda'),
        ),
    ]
