# Generated by Django 3.1.1 on 2020-09-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('C$', 'C$'), ('$', '$')], default='C$', max_length=50, verbose_name='Moneda'),
        ),
    ]
