# Generated by Django 3.1.1 on 2020-09-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_auto_20200921_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_show',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de categoría a mostrar'),
        ),
    ]
