# Generated by Django 3.1.1 on 2020-09-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_category_category_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_text',
            field=models.BooleanField(default=False),
        ),
    ]
