# Generated by Django 3.1.1 on 2020-09-26 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_restaurant_restaurant_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_text',
            new_name='restaurant_test',
        ),
    ]
