# Generated by Django 3.1.1 on 2020-12-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_restaurant_clasification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='fotos_categorias'),
        ),
    ]
