# Generated by Django 3.1.1 on 2020-12-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_auto_20201222_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/default_photos/403_error.jpg', upload_to='fotos_categorias'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='/default_photos/403_error.jpg', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='foto_portada',
            field=models.ImageField(default='/default_photos/403_error.jpg', upload_to='fotos_portadas'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='foto_portada_secundaria',
            field=models.ImageField(default='/default_photos/403_error.jpg', upload_to='fotos_portadas'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='foto_qr',
            field=models.ImageField(default='/default_photos/403_error.jpg', upload_to='qrs'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='foto_restaurante',
            field=models.ImageField(default='/default_photos/403_error.jpg', upload_to='fotos_restaurantes'),
        ),
    ]
